- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
    - id: check-ast
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-docstring-first
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: flake8
      args: [--max-line-length=120]
      excludes:
        - blog/
        - main/
        - manage.py
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
  sha: master
  hooks:
    - id: pep257
      excludes:
        - blog/
        - main/
        - manage.py
