# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='is_approved',
        ),
    ]
